// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMSnnRqyZSUmKBiUgYtSScXmmY0fHIebM',
    appId: '1:360614184890:web:25c87bf166e109f957bf83',
    messagingSenderId: '360614184890',
    projectId: 'iot-loker-app-nibm',
    authDomain: 'iot-loker-app-nibm.firebaseapp.com',
    storageBucket: 'iot-loker-app-nibm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZfz0t0t7CFZqR13lL5dMnCZRxY1AwkA',
    appId: '1:360614184890:android:de4f973365b5e2a457bf83',
    messagingSenderId: '360614184890',
    projectId: 'iot-loker-app-nibm',
    storageBucket: 'iot-loker-app-nibm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1RWhx3DGsXSCvsBk4jywV9nAsZcSo8U',
    appId: '1:360614184890:ios:775d7cd167025c5c57bf83',
    messagingSenderId: '360614184890',
    projectId: 'iot-loker-app-nibm',
    storageBucket: 'iot-loker-app-nibm.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG1RWhx3DGsXSCvsBk4jywV9nAsZcSo8U',
    appId: '1:360614184890:ios:775d7cd167025c5c57bf83',
    messagingSenderId: '360614184890',
    projectId: 'iot-loker-app-nibm',
    storageBucket: 'iot-loker-app-nibm.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMSnnRqyZSUmKBiUgYtSScXmmY0fHIebM',
    appId: '1:360614184890:web:00bc9e1523b3dd1a57bf83',
    messagingSenderId: '360614184890',
    projectId: 'iot-loker-app-nibm',
    authDomain: 'iot-loker-app-nibm.firebaseapp.com',
    storageBucket: 'iot-loker-app-nibm.firebasestorage.app',
  );
}
